name: AlarmClockSimulator
options:
  bundleIdPrefix: com.meeglosh
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "7K9WY5T49S" # Kenzora Games
    CODE_SIGN_STYLE: Automatic

targets:
  AlarmClockSimulator:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AlarmClockSimulator
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.meeglosh.AlarmClockSimulator
        CODE_SIGN_ENTITLEMENTS: AlarmClockSimulator/AlarmClockSimulator.entitlements
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "5"
    info:
      path: AlarmClockSimulator/Info.plist
      properties:
        UILaunchScreen: {}
        UIAppFonts:
          - DSEG7Classic-Bold.ttf
        ITSAppUsesNonExemptEncryption: false
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown

  AlarmClockSimulatorTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AlarmClockSimulatorTests
      - path: Configuration.storekit
        buildPhase: resources
    dependencies:
      - target: AlarmClockSimulator
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/AlarmClockSimulator.app/AlarmClockSimulator"
        BUNDLE_LOADER: "$(TEST_HOST)"

schemes:
  AlarmClockSimulator:
    build:
      targets:
        AlarmClockSimulator: all
        AlarmClockSimulatorTests: [test]
    test:
      targets:
        - AlarmClockSimulatorTests
    run:
      config: Debug
      storeKitConfiguration: Configuration.storekit
